### ISSUE TITLE
Add more explicit sources of strings

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-translate#1]
### Problem

In `jupyterlab-tour`, we can now define the tours through the settings. This means the strings will not be part of the places looked for text to be translated.

> If I got it right, those are extracting by parsing the source code and taking some specified key in settings files.

I can see multiple case of string requiring to be translated that are not in the code directly (in particular in settings to customize UI elements).

Would it make sense to tell jupyterlab-translate 
- to load a specific file containing such strings
- to load any string in the settings json that have a specific annotation like `"__A to-be-translated string"`

> I have just started looking into all the machinery involved with translation. So I may definitely have missed some steps.

**Comment by goanpeca** [comment]
@fcollonval by default `jupyterlab-translate` will parse the settings properties and grab those strings so they are available fro translation.

If you mean you are using another key different from properties to define the tours, then yes, we will need to either add a CLI so that extra keys can also be grabbed and included.

**Comment by fcollonval** [comment]
> If you mean you are using another key different from properties to define the tours, then yes, we will need to either add a CLI so that extra keys can also be grabbed and included.

Yes this is exactly what I need

**Comment by fcollonval** [comment]
@bollwyvl with your experience of object built from data description. What would be a good generic approach to automagically extract strings that need translation from the data file?

I saw that [gettext-extract](https://github.com/sinedied/gettext-extract) for html allows to specify an element. But for JSON using a simple annotation sounds good enough:

> specific annotation like `"__A to-be-translated string"`

**Comment by bollwyvl** [comment]
I'm pretty :-1: on introducing a new in-data syntax... that already conflicts with markdown, etc. 

For well-defined things (such as JSON schema) we could _know_ a few things (`title`, `description`) are internationalize-able, but there isn't much prior art from [schema-town](https://github.com/json-schema-org/json-schema-spec/issues/53) for making them (much less instances of them) internationalized. For example, it's devilishly hard to determine when a `default` string is _really_ a `string`, or whether it's actually something for humans. Or a `patternProperty`.

Looking to other standards:
- JSON-LD is robust as hell, as it has a `@lang` primitive
  -  but requires being _really_ precise as to the semantic meaning of a given JSON blob, as you basically need a perfect round-trip context from the concrete JSON
- the Web Annotation Data Model inherits JSON-LD (as _one_ serialization) but also introduces [selectors](https://www.w3.org/TR/annotation-model/#selectors)
  - there is no dedicated `purpose` or `motivation` for translation
  - while there is no native selector model for JSON, and json-pointer isn't always up to the task
    - there is, however, a `TextQuoteSelector` but this would be relatively weak over time, if the original text changed  
- the [WebExtension API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization) also has a JSON-based storage format, but doesn't help particularly _for_ JSON.

Anyhow, so I don't think this leaves me any particular automagic tools.... i'll have to think about whether some of the above could be synthesized into something.

**Comment by bollwyvl** [comment]
Another, somewhat heavy-handed approach would be to treat these inputs as templates, such that template-based approaches could be brought to bear. On the server side, this could be the exact same things as HTML, e.g. jinja.

So, notebook settings would be like:
```json
"properties": {
  "codeCellConfig": {
    "title": "{{ _('Code Cell Configuration') }}",
```

The disadvantage to this is that automated tools like `json-schema-to-ts`, which _use_ the human-readable `title` to build up code names, e.g. `interface CodeCellConfiguration` would need to have pre-processing applied, which makes it harder to reason about the source of truth, one of the _huge_ advantages to schema in the first place.

Further, in cases like `jupyterlite`, which naively use the schema _at rest_, the un-processed content would look very strange indeed... though if there was a well-established contract, we would be able to emulate `jinja2` with `nunjucks`, to a point.

**Comment by fcollonval** [comment]
Thanks a lot for the documented reply.

**Comment by fcollonval** [comment]
I'll go for the jinja2 approach.
