### ISSUE TITLE
Refactor/remove automated version detection?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-translate#4]
`get_version` is trying hard to deduce the version of package:

https://github.com/jupyterlab/jupyterlab-translate/blob/9c518200c39c431f91ba4c16d162e56f0253ba14/jupyterlab_translate/utils.py#L31-L86

Not hard enough. With migration to federated extensions this does not seem to be sufficient, as seen in https://github.com/jupyterlab/language-packs/pull/28

I don't see a universal way to get a version. For one, let's look at the structure of jupyterlab-lsp monorepo:

<details>

```
.
├── atest
│   ├── 00_Smoke.robot
│   ├── 01_Editor.robot
│   ├── 02_Settings.robot
│   ├── 03_Notebook.robot
│   ├── 04_Interface
│   ├── 05_Features
│   ├── 06_Style.robot
│   ├── 07_Configuration.robot
│   ├── config.py
│   ├── examples
│   ├── fixtures
│   ├── __init__.robot
│   ├── Keywords.robot
│   ├── logcheck.py
│   ├── mouse_over_extension.py
│   ├── ports.py
│   └── Variables.robot
├── binder
│   ├── environment.yml
│   └── postBuild
├── CHANGELOG.md
├── CONTRIBUTING.md
├── docs
│   ├── Architecture.ipynb
│   ├── CHANGELOG.ipynb
│   ├── Configuring.ipynb
│   ├── conf.py
│   ├── Contributing.ipynb
│   ├── dot
│   ├── Extending.ipynb
│   ├── format_markdown.py
│   ├── images
│   ├── index.ipynb
│   ├── __init__.py
│   ├── Installation.ipynb
│   ├── Language Servers.ipynb
│   ├── Releasing.ipynb
│   ├── Roadmap.ipynb
│   ├── rtd.yml
│   ├── _static
│   └── _templates
├── examples
│   ├── Magics_and_rpy2.ipynb
│   ├── Python.ipynb
│   └── screenshots
├── lerna.json
├── LICENSE
├── package.json
├── packages
│   ├── code-jumpers
│   ├── completion-theme
│   ├── _example-extractor
│   ├── jupyterlab-lsp
│   ├── lsp-ws-connection
│   ├── metapackage
│   ├── theme-material
│   ├── theme-vscode
│   ├── tsconfigbase.json
│   └── tsconfig.eslint.json
├── python_packages
│   ├── jupyterlab_lsp
│   └── jupyter_lsp
├── README.md
├── requirements
│   ├── atest.txt
│   ├── atest.yml
│   ├── dev.txt
│   ├── docs.txt
│   ├── docs.yml
│   ├── github-actions.yml
│   ├── lab.txt
│   ├── lint.yml
│   ├── prod.txt
│   └── utest.txt
├── scripts
│   ├── atest.py
│   ├── bump_versions.py
│   ├── combine.py
│   ├── distcheck.py
│   ├── docs.py
│   ├── integrity.py
│   ├── jedi_cache.py
│   ├── lint.py
│   ├── nblint.py
│   ├── publish_pypi.sh
│   ├── tectonic_cache.py
│   └── utest.py
├── setup.cfg
├── versions.py
└── yarn.lock
```

</details>

The thing is we don't have a logical place where the single version for translations can be extracted from **because is is a monrepo**.

I am not convinced that making assumptions about the repository structure is a good to deduce the version.

The alternatives I see as much easier:
- specify the version explicitly in https://github.com/jupyterlab/language-packs/blob/master/repository-map.yml (which will require bumping the version here, but theoretically we could query for the latest version from GitHub API for the repositories which are on GitHub)
- explicitly define a file that extension authors should put the version in for the translation machinery to pick it up (which may be annoying to extension authors)

**Comment by jasongrout** [comment]
I'm trying to understand who needs what package's version and when? Can you help answer those context questions?

**Comment by krassowski** [comment]
Sorry for the vague ticket. The `.pot` files can (and probably should but I am not sure about it) include a version of the package to be translated in `Project-Id-Version: NAME VERSION` line. In case of JupyterLab the `NAME` is JupyterLab, and in case of extensions the `NAME` is the name of the extension. I now see that some projects omit the `VERSION` part.

I tried to update the translation template files but it turns out that version extraction no longer works - for example `dask_extension.pot` in [this PR](https://github.com/jupyterlab/language-packs/pull/28/files#diff-d73087aa61c67891aed5a585bba9412c5aa7fa52eaa43c003d3134f0b4a5e03d).

Maybe we can omit the version in extensions, but I have a feeling that it might cause issues further down the line. Sorry, I have no experience with translations, just trying to help with this (excellent, but a bit stalled) effort.

**Comment by krassowski** [comment]
One option would be to look up the most recent git tag with `git describe`.

**Comment by goanpeca** [comment]
@krassowski what do you think of leaving it in, but if it is not found raise an error so that it needs to be specified manually?
